apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-cert-ocp4-placement-rhacm
  namespace: acm-policies
placementRef:
  name: rhacm-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-cert-rhacm
    apiGroup: policy.open-cluster-management.io
    kind: Policy
