apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: 3scale-configuration-policy-local-cluster
placementBindingDefaults:
  name: 3scale-configuration-policy-local-cluster
policyDefaults:
  namespace: acm-policies
  complianceType: musthave
  remediationAction: enforce
  severity: medium
  placement:
    placementName: rhacm-placement # Assuming the same placement as ingress/logging/monitoring
policies:
  - name: 3scale-configuration-policy-local-cluster
    manifests:
      - path: local-cluster