apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: 3scale-configuration-policy-all-cluster
placementBindingDefaults:
  name: 3scale-configuration-policy-all-cluster
policyDefaults:
  namespace: acm-policies
  complianceType: musthave
  remediationAction: enforce
  severity: medium
  placement:
    placementName: dap-ipi01-placement
policies:
  - name: 3scale-configuration-policy-all-cluster
    manifests:
      - path: all-cluster