apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-cert-ocp4-placement-dap
  namespace: acm-policies
placementRef:
  name: dap-ipi01-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-cert-dap
    apiGroup: policy.open-cluster-management.io
    kind: Policy
